application: guestbook5696
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /getquestion
  script: server.app

- url: /getcategory
  script: server.app 

- url: /questions
  script: server.app 

- url: /parsetk
  script: server.app
  login: admin
  secure: always

libraries:
- name: jinja2
  version: latest

- name: pycrypto
  version: latest

builtins:
- remote_api: on
- deferred: on