application: guestbook5696
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: latest

- name: pycrypto
  version: latest

builtins:
- remote_api: on
